version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
    - db-volume:/var/lib/mysql:Z
    - ./mysql-initdb:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    command:
    - "--max_allowed_packet=128M"
    - "--character-set-server=utf8"
    - "--collation-server=utf8_unicode_ci"

  olt:
    image: registry.gitlab.com/zentekmx/ztst/docker-openltablets
    depends_on:
    - mysql
    ports:
    - "4000:4000"
    volumes:
    - olt-volume:/root/.openl
    links:
    - mysql

volumes:
    db-volume:
    olt-volume:
